### 회원가입

POST http://localhost:8080/auth/signUp
Content-Type: application/json

{
  "email": "dev",
  "password": "1234",
  "name": "ino"
}


### 로그인

POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "dev",
  "password": "1234"
}


### 메인

GET localhost:8080/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZXYiLCJyb2xlIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTcyNDI0MjA2NywiZXhwIjoxNzI0MjQyNjY3fQ.UVqKywn5HEP7jzOLsa9z-Fo4DJFWvHvCPR7UjVtOzWk


### 로그아웃

DELETE localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZXYiLCJyb2xlIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTcyNDE3MTA4MSwiZXhwIjoxNzI0MTcxNjgxfQ.5SB5ldJabQHJtQB8xJbwFN9Kv8saySMTakGTNOak5uo
