### 회원가입

POST http://localhost:8080/auth/signUp
Content-Type: application/json

{
  "email": "dev",
  "password": "1234",
  "name": "ino"
}


### 로그인

POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "dev",
  "password": "1234"
}


### test 로그인

GET localhost:8080/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZXYiLCJyb2xlIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTcyNDE3MTI1OCwiZXhwIjoxNzI0MTcxODU4fQ.Zleo-zytnry28WKRhQ3IURA0fSzvIF7y98yyzYlVIJ4


### 로그아웃

DELETE localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZXYiLCJyb2xlIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTcyNDE3MTA4MSwiZXhwIjoxNzI0MTcxNjgxfQ.5SB5ldJabQHJtQB8xJbwFN9Kv8saySMTakGTNOak5uo
